import { type ReactNode } from "react";
import { type Metadata } from "next";
import { Inter } from "next/font/google";

import { Providers } from "@/app/providers";

import { cn } from "@/shared/utils";

import "../config/style/global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "min-h-screen bg-background font-sans antialiased")}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
